import { Staatliches } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./layout.module.css";

const staatliches = 
  Staatliches({ 
    weight: '400', 
    subsets: ["latin"],
    style: ["normal"] });

export const metadata = {
  title: "Citas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={staatliches.className}>
            <nav className={styles.nav}>
              <li><Link href="/"  className={styles.label}>Home</Link></li>
              <li><Link href="/contacto"  className={styles.label}>Contacto</Link></li>
              <li><Link href="/Reserva" className={styles.label}>Reserva</Link></li>
              <li><Link href="/SobreNosotros" className={styles.label}>Sobre Nosotras</Link></li>
              <li><Link href="/FAQS" className={styles.label}>FAQS</Link></li>
            </nav>
          {children}
        </body>
    </html>
  );
}
