import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <nav className={styles.nav}>
              <li><Link href="/"  className={styles.label}>Contacto</Link></li>
              <li><Link href="/" className={styles.label}>Reserva</Link></li>
              <li><Link href="/" className={styles.label}>Sobre Nosotros</Link></li>
              <li><Link href="/" className={styles.label}>FAQS</Link></li>
            </nav>

          {children}
        </body>
    </html>
  );
}
